### ISSUE TITLE
Unclear how to generate `queries/{*.scm}`  files for syntax highlighting

### ISSUE THREAD

**Issue by thor314** [Decurity/tree-sitter-circom#3]
I would like to use your work to generate syntax highlighting files, [as documented by tree-sitter](https://tree-sitter.github.io/tree-sitter/syntax-highlighting). On running:

```sh
cargo binstall -y tree-sitter-cli
tree-sitter generate
```

It would appear no syntax highlighting scheme files are generated. 

Running `python -m build` build script also seems to break.

**Comment by Frodan** [comment]
Hi, `.scm` files are not generated automatically; they should be manually created by the developer. 

I will try to add syntax highlight support soon.
